
services:
  nginx:
    container_name: nginx
    hostname: nginx_host
    image: nginx:riad
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    networks:
      - webnet
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    hostname: wordpress_host
    image: wordpress:riad
    build: ./requirements/wordpress/.
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - webnet
    ports:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  mariadb:
    container_name: mariadb
    hostname: mariadb_host
    image: mariadb:riad
    build: ./requirements/mariadb/.
    env_file:
      - .env
    networks:
      - webnet 
    ports:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
  adminer:
    container_name: adminer
    hostname: adminer_host
    image: adminer:riad
    build: ./requirements/bonus/adminer/.
    networks:
      - webnet
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mariadb
  my_website:
    container_name: my_website
    hostname: my_website_host
    image:  my_website:riad
    build: ./requirements/bonus/my_website/.
    networks:
      - webnet
    ports:
      - "8000:80"
    restart: always
  redis:
    container_name: redis
    hostname: redis_host
    image: redis:riad
    build: ./requirements/bonus/redis/.
    networks:
      - webnet
    ports:
      - "6379"
    depends_on:
      - wordpress
    restart: always
  portainer:
    container_name: portainer
    hostname: portainer_host
    build: ./requirements/bonus/portainer/.
    image: portainer:riad
    networks:
      - webnet
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
  
  

networks:
  webnet:
      name: net_bridge

volumes:
  mariadb_data:
    name: mariadb
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress_data:
    name: wordpress
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  portainer_data:
    name: portainer
    driver_opts:
      type: none
      device: /home/${USER}/data/portainer
      o: bind