FROM debian:bullseye

RUN apt update && apt upgrade -y && \
    apt install -y wget php7.4 php-fpm php-mysqli

COPY ./tools/script.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/script.sh

CMD [ "/usr/local/bin/script.sh" ]
